name: CI Pipeline

on:
  push:

jobs:
  build-test-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal

      - name: Build Docker image
        run: |
          docker build -t mercedespartstracker:latest .

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform validate
        run: terraform validate
